/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard/index'
import { Route as DashboardOrderRouteImport } from './routes/_dashboard/order'
import { Route as DashboardDemoRouteImport } from './routes/_dashboard/demo'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as DashboardOrderDetailIdRouteImport } from './routes/_dashboard/order-detail.$id'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardOrderRoute = DashboardOrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardDemoRoute = DashboardDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrderDetailIdRoute = DashboardOrderDetailIdRouteImport.update({
  id: '/order-detail/$id',
  path: '/order-detail/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/sign-in': typeof authSignInRoute
  '/demo': typeof DashboardDemoRoute
  '/order': typeof DashboardOrderRoute
  '/': typeof DashboardIndexRoute
  '/order-detail/$id': typeof DashboardOrderDetailIdRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/demo': typeof DashboardDemoRoute
  '/order': typeof DashboardOrderRoute
  '/': typeof DashboardIndexRoute
  '/order-detail/$id': typeof DashboardOrderDetailIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/_dashboard/demo': typeof DashboardDemoRoute
  '/_dashboard/order': typeof DashboardOrderRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/order-detail/$id': typeof DashboardOrderDetailIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/sign-in' | '/demo' | '/order' | '/' | '/order-detail/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/sign-in' | '/demo' | '/order' | '/' | '/order-detail/$id'
  id:
    | '__root__'
    | '/_dashboard'
    | '/(auth)/sign-in'
    | '/_dashboard/demo'
    | '/_dashboard/order'
    | '/_dashboard/'
    | '/_dashboard/order-detail/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/order': {
      id: '/_dashboard/order'
      path: '/order'
      fullPath: '/order'
      preLoaderRoute: typeof DashboardOrderRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/demo': {
      id: '/_dashboard/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DashboardDemoRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/order-detail/$id': {
      id: '/_dashboard/order-detail/$id'
      path: '/order-detail/$id'
      fullPath: '/order-detail/$id'
      preLoaderRoute: typeof DashboardOrderDetailIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardDemoRoute: typeof DashboardDemoRoute
  DashboardOrderRoute: typeof DashboardOrderRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardOrderDetailIdRoute: typeof DashboardOrderDetailIdRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardDemoRoute: DashboardDemoRoute,
  DashboardOrderRoute: DashboardOrderRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardOrderDetailIdRoute: DashboardOrderDetailIdRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
